name: Deploy Preview

on: [pull_request]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required for commenting on pull requests for private repos
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}


jobs:
  deploy-preview:
    environment: 
      name: Neon Preview
      url: ${{ steps.deploy.outputs.preview_url }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
            echo "DATABASE_URL=${PR_${{ github.event.number }}_DATABASE_URL}" >> "$GITHUB_ENV"
            echo "DIRECT_URL=${PR_${{ github.event.number }}_DATABASE_URL_UNPOOLED}" >> "$GITHUB_ENV"

      - run: |
            npx prisma generate
            npx prisma migrate deploy

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: echo preview_url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          # GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ env.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}
